# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'welfare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for welfare
  pod 'OneSignal'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'AFNetworking'
  pod 'UIAlertView-Blocks'
  pod 'Alamofire', '~> 4.4'

  target 'welfareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'welfareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
